### ISSUE TITLE
Emulator drops out

### ISSUE THREAD

**Issue by kingvillain** [yifanlu/PSXperia#10] opened 2011-08-11 22:00 UTC
I finally successfully generated my first game with this great tool, it installed no problems and icon shows as it should, however when I start the game it briefly shows "updating" then drops back out to droid menu again.

Used files from my Crash CRC3b6a23c1.

**Comment by yifanlu** [comment] 2011-08-11 22:02
Can you send me the APK that you generated? Also, can you copy the Android logcat here?

**Comment by kingvillain** [comment] 2011-08-11 22:29
I am struggling to work out how to get the logcat, here is the APK:
-removed-

**Comment by yifanlu** [comment] 2011-08-11 22:32
I'm sorry I didn't see this before, but this is a duplicate of issue #4. This tool does not yet work with that version of Crash Bandicoot. Just keep a lookout on that issue post.

**Closed as completed by yifanlu** 2011-08-11 22:32 UTC
