### ISSUE TITLE
INSTALL_PARSE_FAILED_NO_CERTIFICATES

### ISSUE THREAD

**Issue by woogers** [yifanlu/PSXperia#3] opened 2011-08-11 17:30 UTC
I told you about this on xda, but you said re-report it, so here I am.

Generates the apk with no errors. 
Copy data and apk to phone.
Install apk with phone's Package Manager, "Application Not Installed."
Fire up adb on command line, adb install <apkname.apk>.
FAILED: INSTALL_PARSE_FAILED_NO_CERTIFICATES

OS: Windows Vista x86 (5.1) 
Device: Sony Ericsson R800x CDMA
Android ver: 2.3.3 Verizon
Java: jdk 1.7.0, jre7

**Comment by yifanlu** [comment] 2011-08-11 17:31
This may be a problem with Java 7, but I'm not sure yet.

**Comment by woogers** [comment] 2011-08-11 17:57
Alright, well now that #2 is solved, once this one gets solved, in theory, I should be good to go. Would it be troubling you to shoot over a resigned apk, or should I just wait?

**Comment by yifanlu** [comment] 2011-08-11 18:00
While I try working it out from my side, if it isn't a pain, you can uninstall Java 7 and re/install Java 6 (or 1.6) and see if that works. If it does, that means that we know exactly what the issue is.

**Comment by woogers** [comment] 2011-08-11 18:03
I'll do that as soon I get back, have to go out for a bit.

**Comment by yifanlu** [comment] 2011-08-11 21:42
I'm going to close it for now since the newest version does jar signing internally. If you get the error still, just open this issue up again.

**Closed as completed by yifanlu** 2011-08-11 21:42 UTC

**Comment by Wutzan** [comment] 2011-08-12 09:01
Getting this issue as well. I got it twice now, first time was from Castlevania: Symphony of the Night when I tried putting a picture with it. Removing the picture fixed the problem. I've tried Chrono Cross with success without picture (didn't try with a picture). But now Resident Evil 2 without picture is giving me this problem. Impossible to install the .apk. I'm using java 6 (1.6) so I can confirm it's not related to the new java version.

OS: Windows 7 64 bit
Android version: 2.3.2

EDIT! Fixed the issue! It seems to be related to the name of the Title ID. I originally had the Title ID as "Resident Evil 2" without the quotes, simply removing the the spaces, "ResidentEvil2", made the .apk install. Thinking over, I remembered that I also renamed Castlevania when it didn't work as well, but thought it was the picture instead.

**Comment by yifanlu** [comment] 2011-08-12 15:06
Yes, title ids must follow android and java'a package name naming convention

**Comment by Wutzan** [comment] 2011-08-12 15:43
Guess the most simple fix would be to block characters like spaces or others from the gui's tool box for Title ID. Would fix all issues unless they use the command window which is unlikely.

**Comment by yifanlu** [comment] 2011-08-12 15:45
It was literally committed a minute before your comment ;)
https://github.com/yifanlu/PSXperia/commit/152154da8c483f5741f3055a0dbadec281600e35
